import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import ReactQueryProvider from "@/provider/ReactQueryProvider"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"
import Providers from "@/provider/Providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <ReactQueryDevtools />
        <body className={inter.className}>
          <Providers>{children}</Providers>
        </body>
      </ReactQueryProvider>
    </html>
  )
}
